topic_synchronizer:
  ros__parameters:
    topics:
      source:
        cloud: /cloud
        image: /image
        camera_info: /camera_info
      output:
        cloud: /cloud/sync
        image: /image/sync
        camera_info: /camera_info/sync
    interval_duration: 500000000.0
    approx_policy: 100.0