topic_synchronizer:
  ros__parameters:
    topics:
      source:
        cmd_vel: /taranis/cmd_vel_stamped
        imu: /imu/data
        joint_states: /joint_states
        odom: /odom
        odom_filtered: /odometry/filtered
        odom_gt: /vicon/odom
      output:
        cmd_vel: /sync/taranis/cmd_vel_stamped
        imu: /sync/imu/data
        joint_states: /sync/joint_states
        odom: /sync/odom
        odom_filtered: /sync/odometry/filtered
        odom_gt: /sync/vicon/odom
    interval_duration: 500000000.0
    approx_policy: 1000.0