topic_synchronizer:
  ros__parameters:
    topics:
      source:
        odom0: /odometry0
        odom1: /odometry1
      output:
        odom0: /odometry0/sync
        odom1: /odometry1/sync
    interval_duration: 500000000.0
    approx_policy: 10